// Language data and example words for the "Everything is Four" application
// This module contains all language-specific data including number words, UI translations, and example words

// Example words for each language
export const exampleWords = {
  en: [
    "programming",
    "mathematics",
    "software",
    "computer",
    "keyboard",
    "language",
    "universe",
    "science",
    "knowledge",
    "learning",
    "technology",
    "algorithm",
    "engineering",
    "development",
    "innovation",
    "creativity",
    "discovery",
    "experiment",
    "research",
    "intelligence",
    "philosophy",
    "psychology",
    "communication",
    "information",
    "entertainment",
    "education",
    "experience",
    "understanding",
    "imagination",
    "fascinating",
  ],
  nl: [
    "programmeren",
    "wiskunde",
    "software",
    "computer",
    "toetsenbord",
    "taal",
    "universum",
    "wetenschap",
    "kennis",
    "leren",
    "technologie",
    "algoritme",
    "ontwikkeling",
    "innovatie",
    "creativiteit",
    "ontdekking",
    "experiment",
    "onderzoek",
    "intelligentie",
    "filosofie",
    "psychologie",
    "communicatie",
    "informatie",
    "entertainment",
    "onderwijs",
  ],
  de: [
    "programmierung",
    "mathematik",
    "software",
    "computer",
    "tastatur",
    "sprache",
    "universum",
    "wissenschaft",
    "wissen",
    "lernen",
    "technologie",
    "algorithmus",
    "ingenieurwesen",
    "entwicklung",
    "innovation",
  ],
};

// Language data - 'magic words' in different languages
// Note: Only including languages where the word for 'four' has exactly 4 letters
export const languageData = {
  nl: {
    name: "Nederlands",
    numberWords: {
      0: "nul",
      1: "een",
      2: "twee",
      3: "drie",
      4: "vier",
      5: "vijf",
      6: "zes",
      7: "zeven",
      8: "acht",
      9: "negen",
      10: "tien",
      11: "elf",
      12: "twaalf",
      13: "dertien",
      14: "veertien",
      15: "vijftien",
      16: "zestien",
      17: "zeventien",
      18: "achttien",
      19: "negentien",
      20: "twintig",
      30: "dertig",
      40: "veertig",
      50: "vijftig",
      60: "zestig",
      70: "zeventig",
      80: "tachtig",
      90: "negentig",
      100: "honderd",
    },
    magicNumber: "vier", // 4 letters
    magicNumberValue: 4,
    ui: {
      title: "Alles is",
      tagline: "Elk woord leidt uiteindelijk tot vier. Probeer het zelf!",
      inputPlaceholder: "Voer een woord in...",
      checkButton: "Controleer",
      suggestButton: "Stel een woord voor",
      conclusion: "Elk woord leidt uiteindelijk tot VIER!",
      howItWorks: "Hoe het werkt",
      step1: "Begin met een willekeurig woord",
      step2: "Tel het aantal letters in het woord",
      step3: "Schrijf dat nummer uit als een woord",
      step4: 'Herhaal stappen 2-3 totdat je "vier" bereikt',
      example: "", // Will be generated dynamically
      shareButton: "Delen",
      shareDialogTitle: "Deel deze ontdekking",
      shareDialogText: "Deel deze link met anderen:",
      copyButton: "Kopiëren",
      copiedMessage: "Gekopieerd naar klembord!",
      errors: {
        invalidInput: "Voer een geldig woord in (alleen letters, maximaal 100 tekens).",
        generalError: "Er is een fout opgetreden. Probeer het opnieuw.",
        loadError: "Applicatiefout: Sommige pagina-elementen konden niet worden geladen. Ververs de pagina."
      },
      accessibility: {
        toggleTheme: "Donkere modus schakelen",
        closeShare: "Deel dialoog sluiten",
        enterWord: "Voer een woord in",
        languageSelect: "Selecteer taal"
      },
      footer: {
        heading: "De Vier Nummer Reeks",
        description1: "Het \"Alles is Vier\" fenomeen is een fascinerende wiskundige curiositeit gebaseerd op woordlengtes. Ongeacht met welk woord je begint, het tellen van de letters en het herhalen van het proces leidt altijd tot het woord \"vier\" (dat 4 letters heeft) wat een stabiele lus creëert.",
        description2: "Dit patroon werkt in meerdere talen waar het woord voor \"vier\" precies 4 letters bevat: Engels (four), Nederlands (vier), Duits (vier), en anderen. Probeer verschillende woorden in verschillende talen om te zien hoe ze allemaal convergeren naar vier!"
      }
    },
  },
  en: {
    name: "English",
    numberWords: {
      0: "zero",
      1: "one",
      2: "two",
      3: "three",
      4: "four",
      5: "five",
      6: "six",
      7: "seven",
      8: "eight",
      9: "nine",
      10: "ten",
      11: "eleven",
      12: "twelve",
      13: "thirteen",
      14: "fourteen",
      15: "fifteen",
      16: "sixteen",
      17: "seventeen",
      18: "eighteen",
      19: "nineteen",
      20: "twenty",
      30: "thirty",
      40: "forty",
      50: "fifty",
      60: "sixty",
      70: "seventy",
      80: "eighty",
      90: "ninety",
      100: "hundred",
    },
    magicNumber: "four", // 4 letters
    magicNumberValue: 4,
    ui: {
      title: "Everything is",
      tagline: "Every word eventually leads to four. Try it yourself!",
      inputPlaceholder: "Enter any word...",
      checkButton: "Check",
      suggestButton: "Suggest a Word",
      conclusion: "Every word eventually leads to FOUR!",
      howItWorks: "How it works",
      step1: "Start with any word",
      step2: "Count the number of letters in the word",
      step3: "Write out that number as a word",
      step4: 'Repeat steps 2-3 until you reach "four"',
      example: "", // Will be generated dynamically
      shareButton: "Share",
      shareDialogTitle: "Share this discovery",
      shareDialogText: "Share this link with others:",
      copyButton: "Copy",
      copiedMessage: "Copied to clipboard!",
      errors: {
        invalidInput: "Please enter a valid word (letters only, max 100 characters).",
        generalError: "An error occurred. Please try again.",
        loadError: "Application error: Some page elements failed to load. Please refresh the page."
      },
      accessibility: {
        toggleTheme: "Toggle dark mode",
        closeShare: "Close share dialog",
        enterWord: "Enter a word",
        languageSelect: "Select language"
      },
      footer: {
        heading: "The Four Number Sequence",
        description1: "The \"Everything is Four\" phenomenon is a fascinating mathematical curiosity based on word lengths. No matter what word you start with, counting its letters and repeating the process will always lead to the word \"four\" (which has 4 letters) creating a stable loop.",
        description2: "This pattern works in multiple languages where the word for \"four\" contains exactly 4 letters: English (four), Dutch (vier), German (vier), and others. Try different words in different languages to see how they all converge to four!"
      }
    },
  },
  de: {
    name: "Deutsch",
    numberWords: {
      0: "null",
      1: "eins",
      2: "zwei",
      3: "drei",
      4: "vier",
      5: "fünf",
      6: "sechs",
      7: "sieben",
      8: "acht",
      9: "neun",
      10: "zehn",
      11: "elf",
      12: "zwölf",
      13: "dreizehn",
      14: "vierzehn",
      15: "fünfzehn",
      16: "sechzehn",
      17: "siebzehn",
      18: "achtzehn",
      19: "neunzehn",
      20: "zwanzig",
      30: "dreißig",
      40: "vierzig",
      50: "fünfzig",
      60: "sechzig",
      70: "siebzig",
      80: "achtzig",
      90: "neunzig",
      100: "hundert",
    },
    magicNumber: "vier", // 4 letters
    magicNumberValue: 4,
    ui: {
      title: "Alles ist",
      tagline:
        "Jedes Wort führt schließlich zu vier. Probieren Sie es selbst!",
      inputPlaceholder: "Geben Sie ein Wort ein...",
      checkButton: "Prüfen",
      suggestButton: "Wort vorschlagen",
      conclusion: "Jedes Wort führt schließlich zu VIER!",
      howItWorks: "Wie es funktioniert",
      step1: "Beginnen Sie mit einem beliebigen Wort",
      step2: "Zählen Sie die Anzahl der Buchstaben im Wort",
      step3: "Schreiben Sie diese Zahl als Wort aus",
      step4: 'Wiederholen Sie die Schritte 2-3, bis Sie "vier" erreichen',
      example: "", // Will be generated dynamically
      shareButton: "Teilen",
      shareDialogTitle: "Diese Entdeckung teilen",
      shareDialogText: "Teilen Sie diesen Link mit anderen:",
      copyButton: "Kopieren",
      copiedMessage: "In die Zwischenablage kopiert!",
      errors: {
        invalidInput: "Bitte geben Sie ein gültiges Wort ein (nur Buchstaben, maximal 100 Zeichen).",
        generalError: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
        loadError: "Anwendungsfehler: Einige Seitenelemente konnten nicht geladen werden. Bitte aktualisieren Sie die Seite."
      },
      accessibility: {
        toggleTheme: "Dunklen Modus umschalten",
        closeShare: "Teilen-Dialog schließen",
        enterWord: "Geben Sie ein Wort ein",
        languageSelect: "Sprache auswählen"
      },
      footer: {
        heading: "Die Vier-Zahlen-Sequenz",
        description1: "Das \"Alles ist Vier\" Phänomen ist eine faszinierende mathematische Kuriosität basierend auf Wortlängen. Egal mit welchem Wort Sie beginnen, das Zählen der Buchstaben und das Wiederholen des Prozesses führt immer zum Wort \"vier\" (das 4 Buchstaben hat) und erzeugt eine stabile Schleife.",
        description2: "Dieses Muster funktioniert in mehreren Sprachen, in denen das Wort für \"vier\" genau 4 Buchstaben enthält: Englisch (four), Niederländisch (vier), Deutsch (vier) und andere. Probieren Sie verschiedene Wörter in verschiedenen Sprachen aus, um zu sehen, wie sie alle zu vier konvergieren!"
      }
    },
  },
};

// Supported languages and URL helpers
export const SUPPORTED_LANGS = new Set(["en", "nl", "de"]);